### PR TITLE
⬆ Upgrade to fh-mbaas-api@6.1.7

### PR DESCRIPTION
**Pull request by grdryn**
The demo cloud app already has 6.1.7 (kind of...it's not really shrinkwrapped properly I think), so this should also.

### CODE REVIEW

**Comment by grdryn** [comment]
@JameelB @witmicko @TommyJ1994 what's the procedure for getting new releases of raincatcher modules? It would be great to have this, and @paolobueno's #56 in a release :) I'll use a git ref until then.

**Comment by grdryn** [comment]
See also https://github.com/feedhenry-raincatcher/raincatcher-simple-store/pull/13

**Comment by tomjackman** [comment]
@grdryn I might be re-bumping this in the next few days again due to this https://github.com/feedhenry/fh-mbaas-api/pull/99

Edit: Maybe sooner, ie today/tomorrow.

**Comment by grdryn** [comment]
@TommyJ1994 Cool. If you do, then please close this and feedhenry-raincatcher/raincatcher-simple-store#13.

**Comment by tomjackman** [comment]
Closing as this will be bumped in https://github.com/feedhenry-raincatcher/raincatcher-user/pull/58.

**Pull request closed without merging**
