### PR TITLE
Use new version of simple store without environment-variable-based configuration

### PR DESCRIPTION
**Pull request by paolobueno**
# Motivation
Pushing configuration of `simple-store` to app

# Changes
- Bump `fh-wfm-simple-store` version
- Modify user store to take in configuration object

ping @nialldonnellyfh @JameelB

### CODE REVIEW

**Comment by paolobueno** [comment]
0cf2c93 published as `0.3.0-alpha.3`

**Review by nialldonnellyfh — COMMENTED** [review]
It seems like the fh-wfm-user module has deviated from the pattern  we are going for.

I think this module should be separate from any store logic and use the pattern we are using for the other modules.

I.e. https://github.com/feedhenry-raincatcher/raincatcher-workorder/pull/11/files#diff-c945a46d13b34fcaff544d966cffcabaR33

**Comment by paolobueno** [comment]
@nialldonnellyfh Does that mean moving the implementation of the store to demo-auth and just publishing topics from this module?

The main difference for the user module is that we have non-trivial manipulation of the data around the password hashing, so providing this logic only through the demo application would force the user to base off his solution on it or copy that logic over to his custom implementation. Also refactoring this along with the persistent storage epic/release would make it harder for current users to migrate.

I think it would be better to capture this refactoring in a separate JIRA for a future version.

**Comment by nialldonnellyfh** [comment]
@paolobueno Yes, I will create a separate JIRA to refactor it.

The non-trivial manipulation should be done in the raincatcher-user module but the calls to store the data should be made using the mediator topics.

**Pull request merged**
